# yolov8-twin-detect.yaml
# YOLOv8n-based object detection model with TwinAttention module

# Parameters
nc: 80  # Number of classes (e.g., COCO has 80)

scales:
  n: [0.33, 0.25, 1024]

backbone:
  # [from, number, module, args]
  - [-1, 1, Conv, [64, 3, 2]]                 # 0
  - [-1, 1, Conv, [128, 3, 2]]                # 1
  - [-1, 3, C2f, [128, True]]                 # 2
  - [-1, 1, Conv, [256, 3, 2]]                # 3
  - [-1, 6, C2f, [256, True]]                 # 4-P3/8
  - [-1, 1, Conv, [512, 3, 2]]                # 5
  - [-1, 6, C2f, [512, True]]                 # 6-P4/16
  - [-1, 1, DWConv, [1024, 3, 2]]             # 7
  - [-1, 3, C2f, [1024, True]]                # 8-P5/32
  - [-1, 1, SPPF, [1024, 5]]                  # 9
  - [-1, 1, ParallelFusionAttention, [256]]   # 10

# Detection Head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]  # 11
  - [[-1, 6], 1, Concat, [1]]                   # 12
  - [-1, 3, C2f, [512]]                         # 13
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]  # 14
  - [[-1, 4], 1, Concat, [1]]                   # 15
  - [-1, 3, C2f, [256]]                         # 16 (P3/8-small)
  - [-1, 1, DWConv, [256, 3, 2]]                # 17
  - [[-1, 13], 1, Concat, [1]]                  # 18
  - [-1, 3, C2f, [512]]                         # 19 (P4/16-medium)
  - [-1, 1, DWConv, [512, 3, 2]]                # 20
  - [[-1, 10], 1, Concat, [1]]                  # 21
  - [-1, 3, C2f, [1024]]                        # 22 (P5/32-large)
  - [[16, 19, 22], 1, Detect, [nc]]             # 23
